ESX = nil

TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(xPlayer)
	PlayerData = xPlayer 
end)

RegisterServerEvent('sync:lights1')
AddEventHandler('sync:lights1', function()
    TriggerClientEvent('lights:Darkblue', -1)
end)
RegisterServerEvent('sync:lights2')
AddEventHandler('sync:lights2', function()
    TriggerClientEvent('lights:Lightblue', -1)
end)
RegisterServerEvent('sync:lights3')
AddEventHandler('sync:lights3', function()
    TriggerClientEvent('lights:Turquoise', -1)
end)
RegisterServerEvent('sync:lights4')
AddEventHandler('sync:lights4', function()
    TriggerClientEvent('lights:Green', -1)
end)
RegisterServerEvent('sync:lights5')
AddEventHandler('sync:lights5', function()
    TriggerClientEvent('lights:Yellow', -1)
end)
RegisterServerEvent('sync:lights6')
AddEventHandler('sync:lights6', function()
    TriggerClientEvent('lights:Gold', -1)
end)
RegisterServerEvent('sync:lights7')
AddEventHandler('sync:lights7', function()
    TriggerClientEvent('lights:Orange', -1)
end)
RegisterServerEvent('sync:lights8')
AddEventHandler('sync:lights8', function()
    TriggerClientEvent('lights:Red', -1)
end)
RegisterServerEvent('sync:lights9')
AddEventHandler('sync:lights9', function()
    TriggerClientEvent('lights:Pink', -1)
end)
RegisterServerEvent('sync:lights10')
AddEventHandler('sync:lights10', function()
    TriggerClientEvent('lights:Violet', -1)
end)
RegisterServerEvent('sync:lights11')
AddEventHandler('sync:lights11', function()
    TriggerClientEvent('lights:Purple', -1)
end)
RegisterServerEvent('sync:lights12')
AddEventHandler('sync:lights12', function()
    TriggerClientEvent('lights:Ultraviolet', -1)
end)